// Autogenerated from Pigeon (v26.2.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


/// Represents a SIM card on the device.
class SimCardInfo {
  SimCardInfo({
    required this.slotIndex,
    required this.phoneNumber,
    this.operator_,
    required this.isActive,
    required this.subscriptionId,
    this.displayName,
  });

  int slotIndex;

  String phoneNumber;

  String? operator_;

  bool isActive;

  int subscriptionId;

  String? displayName;

  List<Object?> _toList() {
    return <Object?>[
      slotIndex,
      phoneNumber,
      operator_,
      isActive,
      subscriptionId,
      displayName,
    ];
  }

  Object encode() {
    return _toList();  }

  static SimCardInfo decode(Object result) {
    result as List<Object?>;
    return SimCardInfo(
      slotIndex: result[0]! as int,
      phoneNumber: result[1]! as String,
      operator_: result[2] as String?,
      isActive: result[3]! as bool,
      subscriptionId: result[4]! as int,
      displayName: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SimCardInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Result of an SMS send operation.
class SmsSendResult {
  SmsSendResult({
    required this.success,
    this.errorCode,
    this.errorMessage,
  });

  bool success;

  String? errorCode;

  String? errorMessage;

  List<Object?> _toList() {
    return <Object?>[
      success,
      errorCode,
      errorMessage,
    ];
  }

  Object encode() {
    return _toList();  }

  static SmsSendResult decode(Object result) {
    result as List<Object?>;
    return SmsSendResult(
      success: result[0]! as bool,
      errorCode: result[1] as String?,
      errorMessage: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SmsSendResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is SimCardInfo) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is SmsSendResult) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return SimCardInfo.decode(readValue(buffer)!);
      case 130:
        return SmsSendResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Host API: called from Dart → Kotlin (native side).
class SmsGatewayHostApi {
  /// Constructor for [SmsGatewayHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  SmsGatewayHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Send an SMS natively via the Android SmsManager.
  /// Returns the result synchronously after attempting to send.
  Future<SmsSendResult> sendSms(String phoneNumber, String message, int? simSlot) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mobile.SmsGatewayHostApi.sendSms$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[phoneNumber, message, simSlot]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as SmsSendResult;
  }

  /// Retrieve information about all active SIM cards on the device.
  Future<List<SimCardInfo>> getSimCards() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mobile.SmsGatewayHostApi.getSimCards$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<SimCardInfo>();
  }
}
