// Autogenerated from Pigeon (v26.2.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.simly.gateway.plugin

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object SmsGatewayApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Represents a SIM card on the device.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SimCardInfo (
  val slotIndex: Long,
  val phoneNumber: String,
  val operator_: String? = null,
  val isActive: Boolean,
  val subscriptionId: Long,
  val displayName: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SimCardInfo {
      val slotIndex = pigeonVar_list[0] as Long
      val phoneNumber = pigeonVar_list[1] as String
      val operator_ = pigeonVar_list[2] as String?
      val isActive = pigeonVar_list[3] as Boolean
      val subscriptionId = pigeonVar_list[4] as Long
      val displayName = pigeonVar_list[5] as String?
      return SimCardInfo(slotIndex, phoneNumber, operator_, isActive, subscriptionId, displayName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      slotIndex,
      phoneNumber,
      operator_,
      isActive,
      subscriptionId,
      displayName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SimCardInfo) {
      return false
    }
    if (this === other) {
      return true
    }
    return SmsGatewayApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Result of an SMS send operation.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SmsSendResult (
  val success: Boolean,
  val errorCode: String? = null,
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SmsSendResult {
      val success = pigeonVar_list[0] as Boolean
      val errorCode = pigeonVar_list[1] as String?
      val errorMessage = pigeonVar_list[2] as String?
      return SmsSendResult(success, errorCode, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      success,
      errorCode,
      errorMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SmsSendResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return SmsGatewayApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class SmsGatewayApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SimCardInfo.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SmsSendResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SimCardInfo -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is SmsSendResult -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Host API: called from Dart → Kotlin (native side).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface SmsGatewayHostApi {
  /**
   * Send an SMS natively via the Android SmsManager.
   * Returns the result synchronously after attempting to send.
   */
  fun sendSms(phoneNumber: String, message: String, simSlot: Long?, callback: (Result<SmsSendResult>) -> Unit)
  /** Retrieve information about all active SIM cards on the device. */
  fun getSimCards(): List<SimCardInfo>

  companion object {
    /** The codec used by SmsGatewayHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      SmsGatewayApiPigeonCodec()
    }
    /** Sets up an instance of `SmsGatewayHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SmsGatewayHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mobile.SmsGatewayHostApi.sendSms$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val phoneNumberArg = args[0] as String
            val messageArg = args[1] as String
            val simSlotArg = args[2] as Long?
            api.sendSms(phoneNumberArg, messageArg, simSlotArg) { result: Result<SmsSendResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SmsGatewayApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SmsGatewayApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mobile.SmsGatewayHostApi.getSimCards$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getSimCards())
            } catch (exception: Throwable) {
              SmsGatewayApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
